DEFAULT_UHPPOTED_MQTT_TOPIC_ROOT: str = "uhppoted/gateway"
DEFAULT_CONTROLLER_COMM_TIMEOUT_SECS: float = 30
DEFAULT_CONTROLLER_REQUEST_REPLY_TIMEOUT: float = 5
DEFAULT_PORTAL_CARDS_LIST_STALE_SECS: float = 30  # temporary testing lower number
DEFAULT_PORTAL_CARDS_LIST_POLL_SECS: float = 5 * 60
